language: node_js
node_js:
  - "6"
  - "6.1"
  - "5"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "5.10"
  - "5.11"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
branches:
  only:
    - master
after_success:
- npm run coveralls
notifications:
  email: false